// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: pharmacy.proto

package pharmacypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckDrugRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DrugCode       string                 `protobuf:"bytes,1,opt,name=drug_code,json=drugCode,proto3" json:"drug_code,omitempty"`
	QuantityNeeded int32                  `protobuf:"varint,2,opt,name=quantity_needed,json=quantityNeeded,proto3" json:"quantity_needed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckDrugRequest) Reset() {
	*x = CheckDrugRequest{}
	mi := &file_pharmacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDrugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDrugRequest) ProtoMessage() {}

func (x *CheckDrugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDrugRequest.ProtoReflect.Descriptor instead.
func (*CheckDrugRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckDrugRequest) GetDrugCode() string {
	if x != nil {
		return x.DrugCode
	}
	return ""
}

func (x *CheckDrugRequest) GetQuantityNeeded() int32 {
	if x != nil {
		return x.QuantityNeeded
	}
	return 0
}

type CheckDrugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugCode      string                 `protobuf:"bytes,1,opt,name=drug_code,json=drugCode,proto3" json:"drug_code,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CurrentStock  int32                  `protobuf:"varint,3,opt,name=current_stock,json=currentStock,proto3" json:"current_stock,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDrugResponse) Reset() {
	*x = CheckDrugResponse{}
	mi := &file_pharmacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDrugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDrugResponse) ProtoMessage() {}

func (x *CheckDrugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDrugResponse.ProtoReflect.Descriptor instead.
func (*CheckDrugResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckDrugResponse) GetDrugCode() string {
	if x != nil {
		return x.DrugCode
	}
	return ""
}

func (x *CheckDrugResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckDrugResponse) GetCurrentStock() int32 {
	if x != nil {
		return x.CurrentStock
	}
	return 0
}

func (x *CheckDrugResponse) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CheckDrugResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrugCode      string                 `protobuf:"bytes,1,opt,name=drug_code,json=drugCode,proto3" json:"drug_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_pharmacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{2}
}

func (x *StockItem) GetDrugCode() string {
	if x != nil {
		return x.DrugCode
	}
	return ""
}

func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrescriptionId string                 `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	AppointmentId  string                 `protobuf:"bytes,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Items          []*StockItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_pharmacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveStockRequest) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *ReserveStockRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveStockResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReservationSuccess   bool                   `protobuf:"varint,1,opt,name=reservation_success,json=reservationSuccess,proto3" json:"reservation_success,omitempty"`
	TransactionReference string                 `protobuf:"bytes,2,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	ErrorDetail          string                 `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_pharmacy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_pharmacy_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveStockResponse) GetReservationSuccess() bool {
	if x != nil {
		return x.ReservationSuccess
	}
	return false
}

func (x *ReserveStockResponse) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *ReserveStockResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

var File_pharmacy_proto protoreflect.FileDescriptor

const file_pharmacy_proto_rawDesc = "" +
	"\n" +
	"\x0epharmacy.proto\x12\x13medcore.pharmacy.v1\"X\n" +
	"\x10CheckDrugRequest\x12\x1b\n" +
	"\tdrug_code\x18\x01 \x01(\tR\bdrugCode\x12'\n" +
	"\x0fquantity_needed\x18\x02 \x01(\x05R\x0equantityNeeded\"\xb1\x01\n" +
	"\x11CheckDrugResponse\x12\x1b\n" +
	"\tdrug_code\x18\x01 \x01(\tR\bdrugCode\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12#\n" +
	"\rcurrent_stock\x18\x03 \x01(\x05R\fcurrentStock\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"D\n" +
	"\tStockItem\x12\x1b\n" +
	"\tdrug_code\x18\x01 \x01(\tR\bdrugCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x9b\x01\n" +
	"\x13ReserveStockRequest\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\tR\rappointmentId\x124\n" +
	"\x05items\x18\x03 \x03(\v2\x1e.medcore.pharmacy.v1.StockItemR\x05items\"\x9f\x01\n" +
	"\x14ReserveStockResponse\x12/\n" +
	"\x13reservation_success\x18\x01 \x01(\bR\x12reservationSuccess\x123\n" +
	"\x15transaction_reference\x18\x02 \x01(\tR\x14transactionReference\x12!\n" +
	"\ferror_detail\x18\x03 \x01(\tR\verrorDetail2\xea\x01\n" +
	"\x0fPharmacyService\x12f\n" +
	"\x15CheckDrugAvailability\x12%.medcore.pharmacy.v1.CheckDrugRequest\x1a&.medcore.pharmacy.v1.CheckDrugResponse\x12o\n" +
	"\x18ReservePrescriptionStock\x12(.medcore.pharmacy.v1.ReserveStockRequest\x1a).medcore.pharmacy.v1.ReserveStockResponseB)Z'services/pharmacy-service/pb;pharmacypbb\x06proto3"

var (
	file_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_proto_rawDescData []byte
)

func file_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pharmacy_proto_rawDesc), len(file_pharmacy_proto_rawDesc)))
	})
	return file_pharmacy_proto_rawDescData
}

var file_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pharmacy_proto_goTypes = []any{
	(*CheckDrugRequest)(nil),     // 0: medcore.pharmacy.v1.CheckDrugRequest
	(*CheckDrugResponse)(nil),    // 1: medcore.pharmacy.v1.CheckDrugResponse
	(*StockItem)(nil),            // 2: medcore.pharmacy.v1.StockItem
	(*ReserveStockRequest)(nil),  // 3: medcore.pharmacy.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil), // 4: medcore.pharmacy.v1.ReserveStockResponse
}
var file_pharmacy_proto_depIdxs = []int32{
	2, // 0: medcore.pharmacy.v1.ReserveStockRequest.items:type_name -> medcore.pharmacy.v1.StockItem
	0, // 1: medcore.pharmacy.v1.PharmacyService.CheckDrugAvailability:input_type -> medcore.pharmacy.v1.CheckDrugRequest
	3, // 2: medcore.pharmacy.v1.PharmacyService.ReservePrescriptionStock:input_type -> medcore.pharmacy.v1.ReserveStockRequest
	1, // 3: medcore.pharmacy.v1.PharmacyService.CheckDrugAvailability:output_type -> medcore.pharmacy.v1.CheckDrugResponse
	4, // 4: medcore.pharmacy.v1.PharmacyService.ReservePrescriptionStock:output_type -> medcore.pharmacy.v1.ReserveStockResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pharmacy_proto_init() }
func file_pharmacy_proto_init() {
	if File_pharmacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pharmacy_proto_rawDesc), len(file_pharmacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_proto = out.File
	file_pharmacy_proto_goTypes = nil
	file_pharmacy_proto_depIdxs = nil
}
